### ISSUE TITLE
App Wont Work (505 Error and other issues)

### ISSUE THREAD

**Issue by qubeley10032** [Cybrarist/Zakaty#2]
Hi, I installed the app using docker, but I keep getting a 505 Error, and cant go beyond the login screen.. I'm not sure why..
The site for the gold API doesnt seem to be working also, I tried using an API from another, but that didnt work, neither did leaving it blank.
I also had to add the DNS to the container because there were some name resolution errors and thee app wouldn't install..

Ive attached the docker-compose.yml file in case that helps. Thanks

```
services:
  zakaty:
    image: cybrarist/zakaty:latest
    ports:
      - 16580:80
    environment:
      DB_CONNECTION: sqlite
     APP_TIMEZONE: Asia/Colombo
     APP_URL: http://localhost:16580
     ASSET_URL: http://localhost:16580
      EXCHANGE_RATE_API_KEY: <got-a-proper-api-key>
      PRECIOUS_METAL_PRICE_API_KEY: 
    volumes:
      - ./database:/app/database/sqlite
    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      n65-zakathy:
        ipv4_address: 10.65.0.10
networks:
  n65-zakathy:
    driver: bridge
    ipam:
      config:
        - subnet: 10.65.0.0/24
          gateway: 10.65.0.1
```
